# Ref: https://securitylab.github.com/research/github-actions-preventing-pwn-requests
# and: https://github.com/JuliaSmoothOptimizers/NLPModels.jl/blob/main/.github/workflows/breakage.yml
name: Breakage

# read-only repo token
# no access to secrets
on:
  pull_request:
  workflow_dispatch:

jobs:
  break:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pkg: [
          "JuliaDynamics/ConcurrentSim.jl",
          #"gerlero/Fronts.jl",  # temporarily disabled until its CI succeeds at least on stable
          "QuantumSavory/QuantumSavory.jl",
          "marcom/FoldRNA.jl",
          "JuliaAstro/CCDReduction.jl",
        ]

    steps:
      - uses: actions/checkout@v5

      # Install Julia
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1
          arch: x64
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1

      # Breakage test
      - name: 'Breakage of ${{ matrix.pkg }}, latest version'
        env:
          URL: ${{ matrix.pkg }}
        run: |
          set -euo pipefail
          set -v
          git clone --depth=1 https://github.com/$URL
          cd "${URL#*/}"
          
          julia -e 'using Pkg;
                pkg"activate .";
                pkg"dev ../";
                pkg"instantiate";
                pkg"build";
                pkg"test";'
