# Ref: https://securitylab.github.com/research/github-actions-preventing-pwn-requests
# and: https://github.com/JuliaSmoothOptimizers/NLPModels.jl/blob/main/.github/workflows/breakage.yml
name: Breakage

# read-only repo token
# no access to secrets
on:
  pull_request:
  workflow_dispatch:

jobs:
  break:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - pkg: "JuliaDynamics/ConcurrentSim.jl"
          - pkg: "gerlero/Fronts.jl"
            pkgrevision: "b8d98120a6a59f96921215295ceb6fb054cb5016"
          - pkg: "QuantumSavory/QuantumSavory.jl"
          - pkg: "marcom/FoldRNA.jl"
          - pkg: "JuliaAstro/CCDReduction.jl"

    steps:
      - uses: actions/checkout@v5

      # Install Julia
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1
          arch: x64
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1

      # Breakage test
      - name: 'Breakage of ${{ matrix.pkg }}'
        env:
          URL: ${{ matrix.pkg }}
          REV: ${{ matrix.pkgrevision }}
          JULIA_PKG_PRECOMPILE_AUTO: "0"  # avoid auto-precompile during instantiate; test will precompile as needed
        run: |
          set -euo pipefail
          set -v
          # Derive folder name (repo name)
          export PKG=$(echo "$URL" | cut -f2 -d/)

          # Shallow fetch either a specific commit (pkgrevision) or master tip
          mkdir -p "$PKG"
          git init "$PKG"
          cd "$PKG"
          git remote add origin https://github.com/$URL
          if [ -n "${REV:-}" ]; then
            git fetch --depth 1 origin "$REV"
            git checkout --detach FETCH_HEAD
          else
            git fetch --depth 1 origin master
            git checkout --detach FETCH_HEAD
          fi

          # Order matters: develop PR first, then instantiate so deps resolve once
          julia --color=yes -e '
            using Pkg
            pkg"activate ."
            Pkg.develop(PackageSpec(path=ENV["GITHUB_WORKSPACE"]))
            pkg"instantiate"
            pkg"build"
            pkg"test"'
